language: php

php:
  - hhvm
  - hhvm-nightly

# Allow hhvm-nightly to fail until https://github.com/facebook/hhvm/issues/4934
# is fixed
matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer install

script: vendor/bin/phpunit tests/
